var last =100; var updated = 'Updated: 9 APRIL';
var mname = [
	'THE TERMINATOR',
	'Terminator 2: Judgement Day',
	'Terminator 3: Rise Of the Machines',
	'Terminator 4: Genisys',
	'Terminator 5: Salvation',
	'FINAL DESTINATION 1',
	'FINAL DESTINATION 2',
	'FINAL DESTINATION 3',
	'FINAL DESTINATION 4',
	'FINAL DESTINATION 5',
	'Night At Museum',
	'Night At Museum: Secret Of The Tomb',
	'Night At Museum: Battle Of The Smithsonian',
	'SHOOTER (Leaked Version)',
	'JHALLE',
	'LAIYE JE YAARIAN',
	'JORA The Second Chapter',
	'JORA 10 NUMBARIA',
	'TWILIGHT',
	'The Twilight Saga: New Moon',
	'The Twilight Saga: Eclipse',
	'The Twilight Saga: Breaking Dawn I',
	'The Twilight Saga: Breaking Dawn II',
	'Wet Women In The Wind',
	'CHASING MAVERICKS',
	'I AM LEGEND',
	'UNDERWATER',
	'AMERICAN KAMASUTRA',
	'THE DARJEELING LIMITED',
	'DETECTIVE DEE',
	'BAD BOYS FOR LIFE',
	'Corona Virus The Silent Killer',
	'PANGA',
	'STREET DANCER 3D',
	'ANGREZI MEDIUM',
	'GLASS',
	'GO!',
	'BLOCKERS',
	'THE GRUDGE',
	'WOLF',
	'BLOODSHOT',
	'TEKKEN 2',
	'TEKKEN 1',
	'GUILTY',
	'OPERATION PARINDEY',
	'IS LOVE ENOUGH SIR',
	'BAAGHI 3',
	'IK SANDHU HUNDA SI',
	'THAPPAD',
	'CHHAPAAK',
	'TANAJI',
	'Shubh Mangal Zyada Saavdhan',
	'BHOOT',
	'GOOD NEWS',
	'ONWARD',
	'THE SPY',
	'THE CORRUPTED',
	'GULLY BOY',
	'COMMANDO 3',
	'PANIPAT',
	'BAGANGG 3',
	'SHUKRANU',
	'MARDAANI 2',
	'HACKED',
	'MALANG',
	'JAWAANI JANEMAN',
	'PATI PATNI AUR WOH',
	'DARBAR',
	'MOTICHOOR CHAKNACHOOR',
	'JAI MUMMY DI',
	'BALA',
	'MADE IN CHINA',
	'HOUSEFULL 4',
	'MARJAAVAAN',
	'NULL'
];
var classname = [
	'terminator hollywood',
	'terminator hollywood',
	'terminator hollywood',
	'terminator hollywood',
	'terminator hollywood',
	'final destination hollywood',
	'final destination hollywood',
	'final destination hollywood',
	'final destination hollywood',
	'final destination hollywood',
	'night at museum hollywood',
	'night at museum hollywood',
	'night at museum hollywood',
	'shooter punjabi',
	'jhalle punjabi',
	'laiye je yaarian punjabi',
	'jora punjabi',
	'jora punjabi',
	'twilight hollywood',
	'twilight hollywood',
	'twilight hollywood',
	'twilight hollywood',
	'twilight hollywood',
	'Wet women wind hollywood',
	'chasing mavericks hollywood',
	'legend hollywood',
	'underwater hollywood',
	'american kamasutra hollywood',
	'the darjeeling limited hollywood',
	'detective dee hollywood',
	'bad boys for life hollywood',
	'corona virus silent killer hollywood',
	'panga bollywood',
	'street dancer 3d bollywood',
	'angrezi medium bollywood',
	'glass  hollywood',
	'go hollywood',
	'blockers hollywood',
	'grudge hollywood',
	'wolf hollywood',
	'bloodshot hollywood',
	'tekken 2 hollywood',
	'tekken 1 hollywood',
	'guilty bollywood',
	'operation parindey bollywood',
	'is love enough sir bollywood',
	'baaghi 3 bollywood',
	'ik sandhu hunda si punjabi',
	'thappad bollywood',
	'chhapaak bollywood',
	'tanaji bollywood',
	'shubh mangal zyada saavdhan bollywood',
	'bhoot bollywood',
	'good news bollywood',
	'onward hollywood',
	'the spy hollywood',
	'the corrupted hollywood',
	'gully boy bollywood',
	'commando 3 bollywood',
	'panipat bollywood',
	'bagangg 3 bollywood',
	'shukranu bollywood',
	'mardaani 2 bollywood',
	'hacked bollywood',
	'malang bollywood',
	'jawaani janeman bollywood',
	'pati patni aur woh bollywood',
	'darbar bollywood',
	'motichoor chaknachoor bollywood',
	'jai mummy di bollywood',
	'bala bollywood',
	'made in china bollywood',
	'housefull 4 bollywood',
	'marjaavaan bollywood',
	'NULL'
]
var bname = [
	'SHOOTER (Leaked Version)',
	'JHALLE',
	'LAIYE JE YAARIAN',
	'JORA The Second Chapter',
	'JORA 10 NUMBARIA',
	'PANGA',
	'STREET DANCER 3D',
	'ANGREZI MEDIUM',
	'GUILTY',
	'OPERATION PARINDEY',
	'IS LOVE ENOUGH SIR',
	'BAAGHI 3',
	'IK SANDHU HUNDA SI',
	'THAPPAD',
	'CHHAPAAK',
	'TANAJI',
	'Shubh Mangal Zyada Saavdhan',
	'BHOOT',
	'GOOD NEWS',
	'GULLY BOY',
	'COMMANDO 3',
	'PANIPAT',
	'BAGANGG 3',
	'SHUKRANU',
	'MARDAANI 2',
	'MALANG',
	'JAWAANI JANEMAN',
	'PATI PATNI AUR WOH',
	'DARBAR',
	'HACKED',
	'MOTICHOOR CHAKNACHOOR',
	'JAI MUMMY DI',
	'BALA',
	'MADE IN CHINA',
	'HOUSEFULL 4',
	'MARJAAVAAN',
	'NULL'
];
var hname = [
	'THE TERMINATOR',
	'Terminator 2: Judgement Day',
	'Terminator 3: Rise Of the Machines',
	'Terminator 4: Genisys',
	'Terminator 5: Salvation',
	'FINAL DESTINATION 1',
	'FINAL DESTINATION 2',
	'FINAL DESTINATION 3',
	'FINAL DESTINATION 4',
	'FINAL DESTINATION 5',
	'Night At Museum',
	'Night At Museum: Secret Of The Tomb',
	'Night At Museum: Battle Of The Smithsonian',
	'TWILIGHT',
	'The Twilight Saga: New Moon',
	'The Twilight Saga: Eclipse',
	'The Twilight Saga: Breaking Dawn I',
	'The Twilight Saga: Breaking Dawn II',
	'Wet Women In The Wind',
	'CHASING MAVERICKS',
	'I AM LEGEND',
	'UNDERWATER',
	'AMERICAN KAMASUTRA',
	'THE DARJEELING LIMITED',
	'DETECTIVE DEE',
	'BAD BOYS FOR LIFE',
	'Corona Virus The Silent Killer',
	'GLASS',
	'GO!',
	'BLOCKERS',
	'THE GRUDGE',
	'WOLF',
	'BLOODSHOT',
	'TEKKEN 2',
	'TEKKEN 1',
	'ONWARD',
	'THE SPY',
	'THE CORRUPTED',
	'NULL'
];
var sname = [
	'SAMANTAR',
	'MADE IN HEAVEN',
	'THE RAIKAR CASE',
	'PANCHAYAT',
	'MONEY HEIST Season 4',
	'STAR TREK PICARD',
	'NAKED',
	'XXX',
	'PAYING GUEST',
	'UFF',
	'THARKI BOSS',
	'Mere Husband Ki Dulhaniya',
	'WHOS YOUR DADDY',
	'STATE OF SIEGE',
	'OZARK Season 3',
	'MONEY HEIST Season 1',
	'MONEY HEIST Season 2',
	'MONEY HEIST Season 3',
	'TOY BOY',
	'DARE ME Season 1 (Hindi)',
	'SHE Season 1',
	'SPECIAL OPS',
	'ASUR Season 1',
	'MENTALHOOD Season 1',
	'BHUAKAAL Season 1',
	'AFSOS',
	'CLASS OF 2020',
	'RANGBAAZ PHIRSE',
	'FLAMES Season 2',
	'KOTA FACTORY',
	'NULL'
];
var sepi = [
	'9',
	'9',
	'7',
	'8',
	'1',
	'10',
	'10',
	'3',
	'1',
	'1',
	'3',
	'3',
	'6',
	'8',
	'10',
	'13',
	'9',
	'8',
	'13',
	'10',
	'7',
	'8',
	'1',
	'1',
	'1',
	'8',
	'11',
	'9',
	'5',
	'5'
];