var last =100; var updated = 'Updated: 11 APRIL';
var mname = [
	'bamfaad',
	'baagi 3',
	'goosebumps 2 haunted halloween',
	'goosebumps',
	'sufna',
	'naukar vahuti da',
	'ardaas karaan',
	'band vaaje',
	'daaka',
	'starwars the rise of star walker',
	'solo a starwars story',
	'rogue one a starwars story',
	'john wick chapter 3 parabellum',
	'world war z',
	'the terminator',
	'terminator 2: judgement day',
	'terminator 3: rise of the machines',
	'terminator 4: genisys',
	'terminator 5: salvation',
	'final destination 1',
	'final destination 2',
	'final destination 3',
	'final destination 4',
	'final destination 5',
	'night at museum',
	'night at museum: secret of the tomb',
	'night at museum: battle of the smithsonian',
	'shooter (leaked version)',
	'jhalle',
	'laiye je yaarian',
	'jora the second chapter',
	'jora 10 numbaria',
	'twilight',
	'the twilight saga: new moon',
	'the twilight saga: eclipse',
	'the twilight saga: breaking dawn i',
	'the twilight saga: breaking dawn ii',
	'wet women in the wind',
	'chasing mavericks',
	'i am legend',
	'underwater',
	'american kamasutra',
	'the darjeeling limited',
	'detective dee',
	'bad boys for life',
	'corona virus the silent killer',
	'panga',
	'street dancer 3d',
	'angrezi medium',
	'glass',
	'go!',
	'blockers',
	'the grudge',
	'wolf',
	'bloodshot',
	'tekken 2',
	'tekken 1',
	'guilty',
	'operation parindey',
	'is love enough sir',
	'ik sandhu hunda si',
	'thappad',
	'chhapaak',
	'tanaji',
	'shubh mangal zyada saavdhan',
	'bhoot',
	'good news',
	'onward',
	'the spy',
	'the corrupted',
	'gully boy',
	'commando 3',
	'panipat',
	'bagangg 3',
	'shukranu',
	'mardaani 2',
	'hacked',
	'malang',
	'jawaani janeman',
	'pati patni aur woh',
	'darbar',
	'motichoor chaknachoor',
	'jai mummy di',
	'bala',
	'made in china',
	'housefull 4',
	'marjaavaan'];
var tagmovies = [
	'bamfaad 2020 bollywood romantic drama',
	'baagi 3 2020 bollywood romantic drama action thriller',
	'goosebumps 2 haunted halloween 2019 hollywood drama action thriller fantasy animation',
	'goosebumps 2015 hollywood drama action thriller fantasy animation',
	'sufna punjabi romantic drama emotional 2020',
	'naukar vahuti da punjabi drama comedy',
	'ardaas karaan punjabi drama comedy',
	'band vaaje punjabi drama comedy',
	'daaka punjabi drama comedy action 2020',
	'starwars the rise of star walker hollywood thriller action 2019',
	'solo a starwars story hollywood thriller action 2018',
	'rogue one a starwars story hollywood thriller action 2016',
	'john wick chapter 3 parabellum hollywood thriller action 2019',
	'world war z hollywood thriller action zombie zombies',
	'terminator hollywood action thriller robot',
	'terminator hollywood action thriller robot',
	'terminator hollywood action thriller robot',
	'terminator hollywood action thriller robot',
	'terminator hollywood action thriller robot',
	'final destination hollywood action thriller',
	'final destination hollywood action thriller',
	'final destination hollywood action thriller',
	'final destination hollywood action thriller',
	'final destination hollywood action thriller',
	'night at museum hollywood drama comedy romantic museum',
	'night at museum hollywood drama comedy romantic museum',
	'night at museum hollywood drama comedy romantic museum',
	'shooter punjabi drama action 2020',
	'jhalle punjabi comedy romantic 2019',
	'laiye je yaarian punjabi comedy romantic ',
	'jora punjabi thriller action 2020',
	'jora punjabi thriller action 2020',
	'twilight hollywood action wolf vampire',
	'twilight hollywood action wolf vampire',
	'twilight hollywood action wolf vampire',
	'twilight hollywood action wolf vampire',
	'twilight hollywood action wolf vampire',
	'Wet women wind hollywood',
	'chasing mavericks hollywood',
	'legend hollywood',
	'underwater hollywood',
	'american kamasutra hollywood',
	'the darjeeling limited hollywood',
	'detective dee hollywood',
	'bad boys for life hollywood',
	'corona virus silent killer hollywood',
	'panga bollywood',
	'street dancer 3d bollywood',
	'angrezi medium bollywood',
	'glass  hollywood',
	'go hollywood',
	'blockers hollywood',
	'grudge hollywood',
	'wolf hollywood',
	'bloodshot hollywood',
	'tekken 2 hollywood',
	'tekken 1 hollywood',
	'guilty bollywood',
	'operation parindey bollywood',
	'is love enough sir bollywood',
	'ik sandhu hunda si punjabi',
	'thappad bollywood',
	'chhapaak bollywood',
	'tanaji bollywood',
	'shubh mangal zyada saavdhan bollywood',
	'bhoot bollywood',
	'good news bollywood',
	'onward hollywood',
	'the spy hollywood',
	'the corrupted hollywood',
	'gully boy bollywood',
	'commando 3 bollywood',
	'panipat bollywood',
	'bagangg 3 bollywood',
	'shukranu bollywood',
	'mardaani 2 bollywood',
	'hacked bollywood',
	'malang bollywood',
	'jawaani janeman bollywood',
	'pati patni aur woh bollywood',
	'darbar bollywood',
	'motichoor chaknachoor bollywood',
	'jai mummy di bollywood',
	'bala bollywood',
	'made in china bollywood',
	'housefull 4 bollywood',
	'marjaavaan bollywood',];
var sname = [
	'samantar',
	'made in heaven',
	'the raikar case',
	'panchayat',
	'money heist season 4',
	'star trek picard',
	'naked',
	'xxx',
	'paying guest',
	'uff',
	'tharki boss',
	'mere husband ki dulhaniya',
	'whos your daddy',
	'state of siege',
	'ozark season 3',
	'money heist season 1',
	'money heist season 2',
	'money heist season 3',
	'toy boy',
	'dare me season 1 (hindi)',
	'she season 1',
	'special ops',
	'asur season 1',
	'mentalhood season 1',
	'bhuakaal season 1',
	'afsos',
	'class of 2020',
	'rangbaaz phirse',
	'flames season 2',
	'kota factory'];
var sepi = [
	'9',
	'9',
	'7',
	'8',
	'1',
	'10',
	'10',
	'3',
	'1',
	'1',
	'3',
	'3',
	'6',
	'8',
	'10',
	'13',
	'9',
	'8',
	'13',
	'10',
	'7',
	'8',
	'1',
	'1',
	'1',
	'8',
	'11',
	'9',
	'5',
	'5'];
var tagseries = [
	'samantar hindi indian thiller comedy 2020',
	'made in heaven hindi indian thiller comedy 2020',
	'the raikar case hindi indian thiller comedy 2020',
	'panchayat hindi indian thiller comedy 2020',
	'money heist season 4 english russian canadian american thiller comedy 2020',
	'star trek picard english russian canadian american thiller comedy 2020',
	'naked hindi indian thiller comedy 2020',
	'xxx hindi indian thiller comedy',
	'paying guest hindi indian thiller comedy',
	'uff hindi indian thiller comedy',
	'tharki boss hindi indian thiller comedy',
	'mere husband ki dulhaniya hindi indian thiller comedy',
	'whos your daddy hindi indian thiller comedy 2020',
	'state of siege hindi indian thiller comedy 2020',
	'ozark season 3 english russian canadian american thiller comedy 2020',
	'money heist season 1 english russian canadian american thiller comedy',
	'money heist season 2 english russian canadian american thiller comedy',
	'money heist season 3 english russian canadian american thiller comedy',
	'toy boy english russian canadian american thiller comedy 2020',
	'dare me season 1 (hindi) english russian canadian american thiller comedy 2020',
	'she season 1 hindi indian thiller comedy 2020',
	'special ops hindi indian thiller comedy 2020',
	'asur season 1 hindi indian thiller comedy 2020',
	'mentalhood season 1 hindi indian thiller comedy 2020',
	'bhuakaal season 1 hindi indian thiller comedy 2020',
	'afsos hindi indian thiller comedy 2020',
	'class of 2020 hindi indian thiller comedy',
	'rangbaaz phirse hindi indian thiller comedy 2019',
	'flames season 2 hindi indian thiller comedy 2019',
	'kota factory hindi indian thiller comedy 2019'];